Code flow
firebase/firebase-admin-python pull request #549
Opened 2021-05-03 15:42 UTC by ScruffyProdigy

Provides an option for developers to specify the OAuth response type for their OIDC provider (either one of these can be set:):

- id_token
- code (if set, must also set the client secret)

2021-05-03 15:45 UTC, ScruffyProdigy commented
@lsirac

2021-06-03 18:01 UTC, hiranya911 requested changes
Looks mostly good. Needs a few tweaks to the public API, and a couple of readability nits.

2021-06-03 18:01 UTC, hiranya911 commented on tests/test_auth_providers.py
> +        {'code_response_type': True, 'client_secret': None},
Also prevent setting both to `False`?

2021-06-07 16:46 UTC, ScruffyProdigy commented on firebase_admin/_auth_providers.py
> +    def response_type(self):
Done

2021-06-07 16:46 UTC, ScruffyProdigy commented on firebase_admin/_auth_providers.py
> +class ResponseTypeProviderConfig(ProviderConfig):
Done

2021-06-07 16:46 UTC, ScruffyProdigy commented on firebase_admin/_auth_providers.py
> +        if id_token_response_type is not None or code_response_type is not None:
Done

2021-06-07 16:46 UTC, ScruffyProdigy commented on firebase_admin/_auth_providers.py
> +        if id_token_response_type is not None or code_response_type is not None:
Done

2021-06-07 16:46 UTC, ScruffyProdigy commented on integration/test_auth.py
> +    assert oidc_provider.response_type.id_token == True
Done

2021-06-07 16:47 UTC, ScruffyProdigy commented on integration/test_auth.py
> +    assert oidc_provider.client_secret == None
Done

2021-06-07 16:47 UTC, ScruffyProdigy commented on tests/test_auth_providers.py
> +        {'code_response_type': True, 'client_secret': None},
Done

2021-06-14 17:59 UTC, hiranya911 requested changes
Looks mostly good. Please fix the errors reported by the linter. Plus couple of minor nits on style.

2021-06-14 17:59 UTC, hiranya911 commented on public/index.html
> +<!DOCTYPE html>
Please remove :)

2021-06-14 17:59 UTC, hiranya911 commented on firebase_admin/_auth_providers.py
> +            raise ValueError("At least one response type must be returned.")
Please use single quotes for string literals.

2021-06-14 17:59 UTC, hiranya911 commented on firebase_admin/_auth_providers.py
> +            raise ValueError("At least one response type must be returned.")
Single quotes here too.

2021-12-01 19:37 UTC, lahirumaramba commented on tests/test_auth_providers.py
> +        mask = ['clientId', 'clientSecret', 'displayName', 'enabled', 'issuer', 'responseType.code', 'responseType.idToken']
The following lines also seem to be triggering more lint errors.
```
Running linter on module tests
************* Module tests.test_auth_providers
tests/test_auth_providers.py:124:0: C0301: Line too long (111/100) (line-too-long)
tests/test_auth_providers.py:208:0: C0301: Line too long (111/100) (line-too-long)
tests/test_auth_providers.py:228:0: C0301: Line too long (124/100) (line-too-long)
tests/test_auth_providers.py:253:0: C0301: Line too long (127/100) (line-too-long)
```

2021-12-01 19:38 UTC, lahirumaramba commented
Thanks @ScruffyProdigy !
Hi @egilmorez please take a look at the reference docs when you get a chance. Thank you!

2021-12-09 22:31 UTC, hiranya911 approved these changes
Thanks. LGTM 👍

2021-12-09 22:51 UTC, lahirumaramba approved these changes

2021-12-09 22:52 UTC, kevinthecheung requested changes

2021-12-09 22:52 UTC, kevinthecheung commented on firebase_admin/_auth_client.py
> +            code_response_type: Sets whether to enable the code response flow for the new provider.
Is this a boolean?

2021-12-09 22:52 UTC, kevinthecheung commented on firebase_admin/_auth_client.py
> +            id_token_response_type: Sets whether to enable the ID token response flow for the new
Is this a boolean?

2021-12-09 23:18 UTC, egilmorez approved these changes
LGTM!

2021-12-10 21:40 UTC, ScruffyProdigy commented on firebase_admin/_auth_client.py
> +            code_response_type: Sets whether to enable the code response flow for the new provider.
Yes. Fixed

2021-12-10 21:40 UTC, ScruffyProdigy commented on firebase_admin/_auth_client.py
> +            id_token_response_type: Sets whether to enable the ID token response flow for the new
Yes. Fixed

2021-12-10 21:47 UTC, kevinthecheung approved these changes

2021-12-14 12:46 UTC, merged